### ISSUE TITLE
More customizability with output structure and location

### ISSUE THREAD

**Issue by destruc7i0n** [minecraft-addon-tools/minecraft-addon-toolchain#2]
Allow for more customizability in regards to output structure and location.
One possible use case would be the ability to output a script directly into a world.

**Comment by AtomicBlom** [comment]
Just going through old issues, how are you feeling about the recent changes?

I haven't really tackled working with .mcworld concepts, but I feel like there's a bit more customizability now.

**Comment by destruc7i0n** [comment]
Honestly, I don't really think it's very necessary at this point for development, as it can be useful to switch to another world to check for world specific bugs and the like...

**Comment by AtomicBlom** [comment]
Cool, I'll close this off.

Long term I'd like to be able to do something for addon makers that are dealing with custom worlds, but that whole piece needs a LOT of thought.
