### ISSUE TITLE
UI scripts are not copied

### ISSUE THREAD

**Issue by abc-55** [minecraft-addon-tools/minecraft-addon-toolchain#4]
Files with the `.js` extention in the `experimental_ui` folder are not put into built resource pack. They are copied to `out/before-browserify`, but not `out/bundled`.

**Comment by AtomicBlom** [comment]
This should be fixed by https://github.com/minecraft-addon-tools/minecraft-addon-toolchain/commit/96e91d31ac26bdf01ab6f39f24304b398ba266a8 and https://github.com/minecraft-addon-tools/minecraft-addon-toolchain/commit/43ae83ee36023853ce2556144db3ce5a9ec85cba
